### ISSUE TITLE
Compatibilty

### ISSUE THREAD

**Issue by SteveEmmerich** [spuder/puppet-gitlab#116]
I know this is a dumb question, since you list the compatibility as 3.x, but will this pupmod work on puppet version 2.7.26 as well? 

Thank you for your time.

**Comment by spuder** [comment]
No, it won't work on 2.x because it requires several things like facter 1.8, parameterized classes, and the anchor pattern which aren't available in older versions.


You could install puppet 3.x on just one node and use masterless puppet to install, or you could skip puppet all together and install gitlab using the omnibus packages. That may be the simplest solution.

**Comment by SteveEmmerich** [comment]
Ok that's what I thought. I will probably go the normal install route, and have puppet ignore it. I wish I could upgrade to 3.x, but I cant for my environment. Thanks for the help.

**Comment by spuder** [comment]
Sure thing, with the new omnibus packaging, it is pretty easy to install. You could write your own wrapper module to download the omnibus package and then do a rpm -U or dpkg -i pretty easily.
