### ISSUE TITLE
use upstream repositories

### ISSUE THREAD

**Issue by igalic** [spuder/puppet-gitlab#150]
22nd of april, [gitlab announced](https://about.gitlab.com/2015/04/22/gitlab-7-10-released/) 7.10, and with it, they also announced a (hard to find) [package repository](https://packagecloud.io/).

from what i gather, [the easiest](https://packages.gitlab.com/gitlab/gitlab-ce/install) is to simply use the [computology/packagecloud](https://forge.puppetlabs.com/computology/packagecloud) module to configure it.

i'd like to get a feel from the community (or just @spuder :) about this approach.

the biggest disadvantage with using the repository (in general, not just via the packagecloud module), is that currently, there's no repository for the enterprise edition.

but, maybe, by the time we're through with it, that'll already change (:

**Comment by igalic** [comment]
i've looked at compoutology/packagecloud for like [15 minutes](https://github.com/computology/computology-packagecloud/issues?utf8=%E2%9C%93&q=author%3Aigalic+)

**Comment by spuder** [comment]
Thanks for finding this. This does look like a great option for the community edition. 

```puppet
include packagecloud

 packagecloud::repo { "gitlab/gitlab-ce":
  type => 'rpm',  # or "deb" or "gem"
 }
```

**Comment by igalic** [comment]
@spuder yes, except, it's pretty much unusable at this stage, https://github.com/computology/computology-packagecloud/issues/11 (and i haven't had time to fix it)

**Comment by ahuffman** [comment]
Yes they've totally moved over to the repositories now, as the aws files no longer appear to be maintained.

I took a look to see what 7.10.x version they've gotten up to today.  They're now on 7.10.4-1-1.  

What I found out is that they've completely restructured the installation.  They now have repositories setup, which does make it a little better for management, but now the install process needs to be completely re-written to include yumrepo resources and packages can then be installed by the default package managers.

Take a look at this page to see how they'd like you to complete the installation now: https://packages.gitlab.com/gitlab/gitlab-ce/install

**Comment by ahuffman** [comment]
Check out what I have in branch issue_140.  I've tried reworking the code to account for this major change this afternoon, but I need a little help getting it over the hurdle.  I've kept it so that it can be backward compatible with the older versions, but still not working due to the config.pp subscribe on stop gitlab's exec.  Let's see if we can get this module fixed again.

**Comment by ahuffman** [comment]
I seem to have a working process now with the packagecloud repository in branch issue_140, with the exception that I'm getting a run error on the repo: 
" puppet-agent[21356]: (/Stage[main]/Gitlab::Install/Packagecloud::Repo[gitlab/gitlab-ce]/Exec[yum_make_cache_gitlab/gitlab-ce]/returns) https://packagecloud.io/gitlab/gitlab-ce/el/6/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 401 Unauthorized"" on the run.  It seems to be a yum repo thing and not a puppet issue at this point.  

Has anyone tried installing manually off of the packagecloud repos?

**Comment by pcfens** [comment]
Rather than trying to use the packagecloud module, why not replicate their manual installation tasks using the more widely accepted yumrepo and apt::source methods?

I've got [something thrown together](https://github.com/pcfens/puppet-gitlab/tree/use_repos) that installs versions >=7.10 from repositories, but falls back to the old method if installing version <7.10. The setting can be overridden using the `gitlab_use_repo` parameter.

This was thrown together quickly so there are likely some issues, but has been tested in CentOS 6.6 and Ubuntu 14.04.

The diff is scarier looking than the number of changes I actually made - wrapping an entire section in a conditional seems to have made a few changes (also my editor stripped a lot of trailing spaces).

**Comment by ahuffman** [comment]
There's some sort of access problem on the packagecloud repos, and I'm getting 401 unauthorized when attempting to use.  I opened an issue with gitlab today on it.  Otherwise I have a reworked install process using packagecloud on my forked repo branch issue_140.  It would work if there wasn't an access issue on the packagecloud repo.  

As for why wouldn't I use the yumrepo resource, I normally would, but finding gitlab is changing many of their delivery methods, I'd rather be following their preferred install method than having to rework things later if they change at this point.  This all started with package names changing as well as packaged downloads etc.  

I tested their manual repo install script today, and I have the same access issues there, so I'm not sure what's going on, and thus the opened issue with gitlab on the topic.

**Comment by ice799** [comment]
Hi:

Sorry for the delayed response. I seem to be having some sort of issue with my GitHub notifications. I'm a co-founder at packagecloud. Let me know how I can help with the issue you are seeing @ahuffman.

Perhaps it might be better to exchange some emails so I can help debug? support@packagecloud.io

**Comment by spuder** [comment]
Looks like gitlab added enterprise edition repo

https://packages.gitlab.com/gitlab/gitlab-ee

I'm working on refactoring the module now to support this

**Comment by ahuffman** [comment]
Sounds good.

**Comment by spuder** [comment]
Module transitioned to here:  https://github.com/vshn/puppet-gitlab
